### ISSUE TITLE
Move the Unpublish field up

### ISSUE THREAD

**Issue by kucrut** [humanmade/Unpublish#14]
As illustrated by the screenshot below, I believe it's best to move the field up (by setting the action priority to `1`).

<img width="282" alt="screen shot 2016-07-28 at 1 54 41 pm" src="https://cloud.githubusercontent.com/assets/67838/17202726/8ea5f378-54cd-11e6-9ee8-7e89840dc069.png">

**Comment by kucrut** [comment]
@peterwilsoncc What do you think?

**Comment by peterwilsoncc** [comment]
Yes, that makes more sense 👍
